library("Rmpfr")
library("ggplot2")
library("reshape2")
setwd("C:/Users/jhvan/OneDrive - Pontificia Universidad Javeriana/2020-03/Analisis Numerico/Talleres/Taller 1/codigo")
source("./methods.R")
source("./utils.R")

f <- function(x) 3*sin(x)^3 - 1 - 4*sin(x)*cos(x)
tol <- toleranciaFactory(-16)
res <- methods.secant(f, mpfr(0, tol$bits), mpfr(2, tol$bits), tol$tol)
print(res)
plot(f, xlim = c(0, 2), col = "red")
title(main = "3*sin(x)^3 - 1 - 4*sin(x)*cos(x)")
abline(h = 0)
abline(v = 0)
abline(v = res$cero, col="blue")